import { useCallback } from "react";
import {
  ReactFlow,
  Background,
  Controls,
  MiniMap,
  addEdge,
  useNodesState,
  useEdgesState,
  MarkerType,
} from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import StudioStepNode from "./StudioStepNode.jsx";

// Phase-1 spike: prove drag-to-connect AND that the OLD Studio design carries
// over. The step nodes use StudioStepNode (generated by `agentpit workflow` from
// the real .ws-* spec) as a React Flow custom node type.
const nodeTypes = { studioStep: StudioStepNode };

const initialNodes = [
  { id: "workflow", type: "input", position: { x: 20, y: 220 }, data: { label: "WORKFLOW" } },
  {
    id: "s1",
    type: "studioStep",
    position: { x: 260, y: 40 },
    data: {
      index: "01",
      name: "Plan the change",
      dynamic: true,
      managerMono: "cl",
      managerColor: "#d9772e",
      managerLabel: "claude",
      ask: false,
      persona: "Break the goal into the smallest correct steps.",
      behavior: "Draft an implementation blueprint from the goal.",
      workers: [{ mono: "cx", color: "#7da0c4", label: "codex" }],
    },
  },
  {
    id: "s2",
    type: "studioStep",
    position: { x: 580, y: 40 },
    data: {
      index: "02",
      name: "Review & harden",
      dynamic: false,
      managerMono: "cx",
      managerColor: "#7da0c4",
      managerLabel: "codex",
      ask: true,
      persona: "",
      behavior: "Adversarially review the diff for correctness and security.",
      workers: [],
    },
  },
  { id: "ghost", type: "output", position: { x: 900, y: 220 }, data: { label: "+ dynamic" } },
];

const initialEdges = [
  { id: "e-wf-s1", source: "workflow", target: "s1", markerEnd: { type: MarkerType.ArrowClosed } },
  { id: "e-s1-s2", source: "s1", target: "s2", markerEnd: { type: MarkerType.ArrowClosed } },
];

export default function App() {
  const [nodes, , onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);

  const onConnect = useCallback(
    (params) =>
      setEdges((eds) =>
        addEdge({ ...params, markerEnd: { type: MarkerType.ArrowClosed } }, eds)
      ),
    [setEdges]
  );

  return (
    <div style={{ width: "100vw", height: "100vh", background: "#0a0d14" }}>
      <ReactFlow
        nodes={nodes}
        edges={edges}
        nodeTypes={nodeTypes}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        onConnect={onConnect}
        fitView
      >
        <Background color="#232a3a" gap={22} />
        <MiniMap pannable zoomable />
        <Controls />
      </ReactFlow>
    </div>
  );
}
